version: "3.8"

services:
  db:
    image: mysql:8
    container_name: hotel-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hotel_db
    volumes:
      - db-data:/var/lib/mysql

  backend:
    image: bdsdmiii/hotel-backend:latest
    container_name: hotel-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/hotel_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    image: bdsdmiii/hotel-frontend:latest
    container_name: hotel-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db-data:
